
@Cartend.Api_HostAddress = http://localhost:5025


GET {{Cartend.Api_HostAddress}}/car_services?carId=76eae11d-6501-4545-8c0d-914008394af3

###

POST {{Cartend.Api_HostAddress}}/car_services
Content-Type: application/json

{
  "carId": "76eae11d-6501-4545-8c0d-914008394af3",
  "servicedBy": "bob",
  "workDone": {
    "wheels": "replaced"
  }
}

###