
@Cartend.Api_HostAddress = http://localhost:5025


GET {{Cartend.Api_HostAddress}}/cars?ownerId=31a1d035-e46b-4d0d-ab36-6c0731f44ce7

###

POST {{Cartend.Api_HostAddress}}/cars
Content-Type: application/json

{
  "ownerId": "31a1d035-e46b-4d0d-ab36-6c0731f44ce7",
  "name": "jazz"
}

###