
@Cartend.Api_HostAddress = http://localhost:5025


GET {{Cartend.Api_HostAddress}}/cars?ownerId=c3ba4780-4fb3-4aa5-a973-2a8a4d87ced5

###

POST {{Cartend.Api_HostAddress}}/cars
Content-Type: application/json

{
  "ownerId": "c3ba4780-4fb3-4aa5-a973-2a8a4d87ced5",
  "name": "see7"
}

###